import type { Ingredient, IngredientId } from "./types";

export const INGREDIENTS: Record<IngredientId, Ingredient> = {
  flour: {
    id: "flour",
    name: "Flour",
    emoji: "🌾",
    pricePerUnit: 1,
    unit: "cup",
    startingAmount: 30,
  },
  sugar: {
    id: "sugar",
    name: "Sugar",
    emoji: "🍬",
    pricePerUnit: 1,
    unit: "cup",
    startingAmount: 25,
  },
  butter: {
    id: "butter",
    name: "Butter",
    emoji: "🧈",
    pricePerUnit: 2,
    unit: "stick",
    startingAmount: 18,
  },
  eggs: {
    id: "eggs",
    name: "Eggs",
    emoji: "🥚",
    pricePerUnit: 1,
    unit: "egg",
    startingAmount: 18,
  },
  milk: {
    id: "milk",
    name: "Milk",
    emoji: "🥛",
    pricePerUnit: 2,
    unit: "cup",
    startingAmount: 22,
  },
  chocolate: {
    id: "chocolate",
    name: "Chocolate",
    emoji: "🍫",
    pricePerUnit: 3,
    unit: "bar",
    startingAmount: 14,
  },
  yeast: {
    id: "yeast",
    name: "Yeast",
    emoji: "🫧",
    pricePerUnit: 2,
    unit: "pkt",
    startingAmount: 10,
  },
  fruit: {
    id: "fruit",
    name: "Fresh Fruit",
    emoji: "🍓",
    pricePerUnit: 2,
    unit: "cup",
    startingAmount: 16,
  },
  coffee_beans: {
    id: "coffee_beans",
    name: "Coffee Beans",
    emoji: "☕",
    pricePerUnit: 3,
    unit: "scoop",
    startingAmount: 14,
  },
  tea_leaves: {
    id: "tea_leaves",
    name: "Tea Leaves",
    emoji: "🍃",
    pricePerUnit: 2,
    unit: "scoop",
    startingAmount: 12,
  },
  icing: {
    id: "icing",
    name: "Sweet Icing",
    emoji: "🧁",
    pricePerUnit: 2,
    unit: "swirl",
    startingAmount: 18,
  },
  lemon: {
    id: "lemon",
    name: "Lemons",
    emoji: "🍋",
    pricePerUnit: 1,
    unit: "lemon",
    startingAmount: 12,
  },
  cinnamon: {
    id: "cinnamon",
    name: "Cinnamon",
    emoji: "🌰",
    pricePerUnit: 2,
    unit: "shake",
    startingAmount: 10,
  },
  pet_mix: {
    id: "pet_mix",
    name: "Pet-Safe Mix",
    emoji: "🐾",
    pricePerUnit: 3,
    unit: "scoop",
    startingAmount: 12,
    petSafe: true,
  },
};

export const INGREDIENT_LIST = Object.values(INGREDIENTS);
