import type { Recipe } from "./types";

/**
 * Recipe registry. Add new recipes here — see README for guidance.
 *
 * Tips:
 *  - Keep `prepMs` between 5-30s; longer prep should pay more.
 *  - Set `unlocked: false` and an `unlockLevel` for late-game treats.
 *  - Each recipe also needs an art asset in src/components/foods/FoodArt.tsx.
 */
export const RECIPES: Recipe[] = [
  // ---------------- Drinks ----------------
  {
    id: "hot_chocolate",
    name: "Hot Chocolate",
    category: "drink",
    station: "drink",
    ingredients: { milk: 1, chocolate: 1 },
    steps: [
      { label: "Warm milk on the stove", durationMs: 3000 },
      { label: "Stir in chocolate until smooth", durationMs: 4000 },
      { label: "Top with a marshmallow swirl", durationMs: 1000 },
    ],
    prepMs: 8000,
    price: 5,
    unlocked: true,
    description: "Steamy, cozy, and snowflake-soft on top.",
    funFact: "Aztec warriors drank chocolate for energy long before us!",
  },
  {
    id: "milkshake",
    name: "Strawberry Milkshake",
    category: "drink",
    station: "drink",
    ingredients: { milk: 1, sugar: 1, fruit: 1 },
    steps: [
      { label: "Blend strawberries with sugar", durationMs: 4000 },
      { label: "Pour over icy milk", durationMs: 3000 },
      { label: "Crown with whipped cream", durationMs: 2000 },
    ],
    prepMs: 9000,
    price: 6,
    unlocked: true,
    description: "Pink, frothy, and giggle-inducing.",
  },
  {
    id: "smoothie",
    name: "Sunshine Smoothie",
    category: "drink",
    station: "drink",
    ingredients: { milk: 1, fruit: 2 },
    steps: [
      { label: "Drop fruit into the blender", durationMs: 3000 },
      { label: "Add a splash of milk", durationMs: 2000 },
      { label: "Whirl until rainbow-smooth", durationMs: 4000 },
    ],
    prepMs: 9000,
    price: 7,
    unlocked: true,
    description: "Fruity sunshine in a glass.",
  },
  {
    id: "lemonade",
    name: "Sparkly Lemonade",
    category: "drink",
    station: "drink",
    ingredients: { lemon: 2, sugar: 1 },
    steps: [
      { label: "Squeeze the lemons", durationMs: 3000 },
      { label: "Stir in sugar", durationMs: 2000 },
      { label: "Add ice & a curly straw", durationMs: 1000 },
    ],
    prepMs: 6000,
    price: 4,
    unlocked: true,
    description: "Tangy, fizzy, summer-in-a-cup.",
  },
  {
    id: "coffee",
    name: "Cozy Coffee",
    category: "drink",
    station: "drink",
    ingredients: { coffee_beans: 1, milk: 1 },
    steps: [
      { label: "Grind the coffee beans", durationMs: 3000 },
      { label: "Brew the espresso", durationMs: 3000 },
      { label: "Top with foamy milk art", durationMs: 2000 },
    ],
    prepMs: 8000,
    price: 5,
    unlocked: true,
    description: "Warm hug for sleepy grown-ups.",
  },
  {
    id: "tea",
    name: "Garden Tea",
    category: "drink",
    station: "drink",
    ingredients: { tea_leaves: 1 },
    steps: [
      { label: "Boil the kettle", durationMs: 3000 },
      { label: "Steep the leaves", durationMs: 3000 },
      { label: "Slice a lemon for the rim", durationMs: 1000 },
    ],
    prepMs: 7000,
    price: 4,
    unlocked: true,
    description: "Calm, leafy, and elegant.",
  },
  {
    id: "mocha",
    name: "Marshmallow Mocha",
    category: "drink",
    station: "drink",
    ingredients: { coffee_beans: 1, chocolate: 1, milk: 1 },
    steps: [
      { label: "Brew a strong espresso", durationMs: 3000 },
      { label: "Melt chocolate into the milk", durationMs: 4000 },
      { label: "Float marshmallows on top", durationMs: 3000 },
    ],
    prepMs: 11000,
    price: 9,
    unlocked: false,
    unlockLevel: 2,
    description: "Coffee + chocolate = magic.",
  },
  {
    id: "pineapple_juice",
    name: "Pineapple Juice",
    category: "drink",
    station: "drink",
    ingredients: { pineapple: 2, sugar: 1 },
    steps: [
      { label: "Chop up pineapple chunks", durationMs: 3000 },
      { label: "Press out the golden juice", durationMs: 3000 },
      { label: "Pour over crushed ice", durationMs: 1500 },
    ],
    prepMs: 7500,
    price: 6,
    unlocked: true,
    description: "Sunshine in a glass — tropical and tangy.",
    funFact: "Pineapples take almost two years to grow!",
  },
  {
    id: "almond_milk",
    name: "Almond Milk",
    category: "drink",
    station: "drink",
    ingredients: { almond: 2, sugar: 1 },
    steps: [
      { label: "Soak the almonds", durationMs: 3000 },
      { label: "Blend with water & honey", durationMs: 4000 },
      { label: "Strain through a soft cloth", durationMs: 2000 },
    ],
    prepMs: 9000,
    price: 6,
    unlocked: true,
    description: "Silky, nutty, and dairy-free.",
  },
  {
    id: "berry_smoothie",
    name: "Berry Glow Smoothie",
    category: "drink",
    station: "drink",
    ingredients: { fruit: 2, milk: 1, sugar: 1 },
    steps: [
      { label: "Mix the berries", durationMs: 4000 },
      { label: "Whip with milk and sugar", durationMs: 4000 },
      { label: "Garnish with a mint leaf", durationMs: 2000 },
    ],
    prepMs: 10000,
    price: 8,
    unlocked: false,
    unlockLevel: 3,
    description: "Bright purple and full of pep.",
  },

  // ---------------- Pastries (assemble at counter) ----------------
  {
    id: "glazed_donut",
    name: "Glazed Donut",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, icing: 1 },
    steps: [
      { label: "Pull a donut from the case", durationMs: 1500 },
      { label: "Dip in shiny glaze", durationMs: 2500 },
      { label: "Box it up with a wink", durationMs: 1000 },
    ],
    prepMs: 5000,
    price: 4,
    unlocked: true,
    description: "Classic ring of joy.",
  },
  {
    id: "sprinkle_donut",
    name: "Sprinkle Donut",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, icing: 1 },
    steps: [
      { label: "Glaze the donut pink", durationMs: 2000 },
      { label: "Shower with rainbow sprinkles", durationMs: 3000 },
    ],
    prepMs: 5500,
    price: 5,
    unlocked: true,
    description: "Confetti you can eat.",
  },
  {
    id: "munchkins",
    name: "Munchkins",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, icing: 1 },
    steps: [
      { label: "Scoop out little dough balls", durationMs: 2000 },
      { label: "Dust in cinnamon sugar", durationMs: 2000 },
      { label: "Pile into a paper cup", durationMs: 1500 },
    ],
    prepMs: 5500,
    price: 5,
    unlocked: true,
    description: "Bite-sized donut holes — a whole handful of joy.",
    funFact: "These tiny treats are made from the spot punched out of a full donut!",
  },
  {
    id: "chocolate_cupcake",
    name: "Chocolate Cupcake",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, chocolate: 1, icing: 1 },
    steps: [
      { label: "Set the cupcake on a paper", durationMs: 1500 },
      { label: "Pipe a chocolate icing swirl", durationMs: 3000 },
      { label: "Crown with a cherry", durationMs: 1500 },
    ],
    prepMs: 6000,
    price: 6,
    unlocked: true,
    description: "Tall, fluffy, and fudgy.",
  },
  {
    id: "blueberry_muffin",
    name: "Blueberry Muffin",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, fruit: 1 },
    steps: [
      { label: "Tuck blueberries into the batter", durationMs: 2000 },
      { label: "Sprinkle sugar on top", durationMs: 2000 },
      { label: "Wrap with a paper liner", durationMs: 1500 },
    ],
    prepMs: 5500,
    price: 5,
    unlocked: true,
    description: "Bursting with juicy little gems.",
  },
  {
    id: "cinnamon_roll",
    name: "Cinnamon Roll",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, butter: 1, cinnamon: 1, icing: 1 },
    steps: [
      { label: "Brush with cinnamon-sugar butter", durationMs: 2500 },
      { label: "Roll into a perfect spiral", durationMs: 2500 },
      { label: "Drizzle with cream icing", durationMs: 2000 },
    ],
    prepMs: 7000,
    price: 7,
    unlocked: true,
    description: "Warm hug shaped like a swirl.",
  },
  {
    id: "butter_cookie",
    name: "Butter Cookie",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, butter: 1, sugar: 1 },
    steps: [
      { label: "Stamp out a flower shape", durationMs: 2000 },
      { label: "Brush with melted butter", durationMs: 2000 },
    ],
    prepMs: 4000,
    price: 4,
    unlocked: true,
    description: "Crumbly, golden, simple, perfect.",
  },

  // ---------------- Oven-baked goods ----------------
  {
    id: "scratch_donut",
    name: "Fresh Donut",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, yeast: 1, sugar: 1, butter: 1 },
    steps: [
      { label: "Mix dough with yeast", durationMs: 5000 },
      { label: "Knead and rise", durationMs: 6000 },
      { label: "Cut rings & fry", durationMs: 5000 },
      { label: "Coat in cinnamon sugar", durationMs: 2000 },
    ],
    prepMs: 18000,
    price: 9,
    unlocked: true,
    description: "Made from real dough — pillowy and golden.",
    funFact: "Fresh-baked donuts pay more because they take real love.",
  },
  {
    id: "scratch_cookies",
    name: "Choc-Chip Cookies",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, butter: 1, sugar: 1, chocolate: 1, eggs: 1 },
    steps: [
      { label: "Cream the butter and sugar", durationMs: 4000 },
      { label: "Fold in chocolate chips", durationMs: 4000 },
      { label: "Scoop dough onto a tray", durationMs: 4000 },
      { label: "Bake until just golden", durationMs: 6000 },
    ],
    prepMs: 18000,
    price: 10,
    unlocked: true,
    description: "Crispy edges, gooey middles.",
  },
  {
    id: "scratch_pie",
    name: "Berry Pie",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, butter: 2, fruit: 2, sugar: 1 },
    steps: [
      { label: "Roll out the pie crust", durationMs: 5000 },
      { label: "Pile in fruit & sugar", durationMs: 4000 },
      { label: "Lattice the top crust", durationMs: 5000 },
      { label: "Bake until bubbling", durationMs: 8000 },
    ],
    prepMs: 22000,
    price: 12,
    unlocked: false,
    unlockLevel: 2,
    description: "A lattice of love over warm berries.",
  },
  {
    id: "decorated_cake",
    name: "Decorated Cake",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, sugar: 2, butter: 2, eggs: 2, icing: 2, chocolate: 1 },
    steps: [
      { label: "Whisk the cake batter", durationMs: 5000 },
      { label: "Bake the layers", durationMs: 8000 },
      { label: "Stack and frost", durationMs: 8000 },
      { label: "Add sprinkles & a cherry", durationMs: 3000 },
    ],
    prepMs: 26000,
    price: 18,
    unlocked: false,
    unlockLevel: 4,
    description: "A celebration in every slice.",
  },
  {
    id: "croissant",
    name: "Buttery Croissant",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, butter: 2, yeast: 1 },
    steps: [
      { label: "Fold butter into dough", durationMs: 6000 },
      { label: "Roll, fold, repeat", durationMs: 6000 },
      { label: "Shape into crescents", durationMs: 4000 },
      { label: "Bake until shatter-flaky", durationMs: 6000 },
    ],
    prepMs: 22000,
    price: 12,
    unlocked: false,
    unlockLevel: 3,
    description: "Layers and layers of buttery joy.",
  },
  {
    id: "chocolate_croissant",
    name: "Chocolate Croissant",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, butter: 2, yeast: 1, chocolate: 2 },
    steps: [
      { label: "Fold butter into dough", durationMs: 6000 },
      { label: "Tuck chocolate batons inside", durationMs: 4000 },
      { label: "Roll up each crescent", durationMs: 4000 },
      { label: "Bake until the chocolate melts", durationMs: 6000 },
    ],
    prepMs: 22000,
    price: 14,
    unlocked: true,
    description: "Flaky layers hugging a molten chocolate heart.",
  },
  {
    id: "white_choc_muffin",
    name: "White Chocolate Sprinkle Muffin",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, butter: 1, chocolate: 1, icing: 1 },
    steps: [
      { label: "Fold white chocolate chips into batter", durationMs: 2500 },
      { label: "Scoop into a paper liner", durationMs: 2000 },
      { label: "Shower with rainbow sprinkles", durationMs: 2000 },
    ],
    prepMs: 7500,
    price: 8,
    unlocked: true,
    description: "Creamy white chocolate, confetti on top.",
  },
  {
    id: "red_velvet_muffin",
    name: "Red Velvet Muffin",
    category: "pastry",
    station: "pastry",
    ingredients: { flour: 1, sugar: 1, butter: 1, chocolate: 1, icing: 1 },
    steps: [
      { label: "Whisk cocoa into ruby batter", durationMs: 2500 },
      { label: "Fill each liner", durationMs: 2000 },
      { label: "Swirl on cream-cheese icing", durationMs: 2500 },
    ],
    prepMs: 8000,
    price: 9,
    unlocked: true,
    description: "Velvety cocoa crumb with tangy cream-cheese swirl.",
  },
  {
    id: "olive_oil_cake",
    name: "Olive Oil Cake",
    category: "scratch",
    station: "scratch",
    ingredients: { flour: 2, sugar: 2, eggs: 2, lemon: 1 },
    steps: [
      { label: "Whisk eggs and sugar fluffy", durationMs: 5000 },
      { label: "Drizzle in golden olive oil", durationMs: 4000 },
      { label: "Zest the lemon into the batter", durationMs: 3000 },
      { label: "Bake until the top is crackly", durationMs: 8000 },
    ],
    prepMs: 22000,
    price: 14,
    unlocked: true,
    description: "Moist, citrusy, with a whisper of fruity olive oil.",
    funFact: "An Italian classic — olive oil keeps this cake tender for days.",
  },

  // ---------------- Pet treats ----------------
  {
    id: "dog_bone",
    name: "Bone Biscuit",
    category: "pet",
    station: "pet",
    ingredients: { flour: 1, pet_mix: 1 },
    steps: [
      { label: "Mix pet-safe dough", durationMs: 4000 },
      { label: "Cut into bone shapes", durationMs: 3000 },
      { label: "Bake until crunchy", durationMs: 3000 },
    ],
    prepMs: 10000,
    price: 5,
    unlocked: true,
    description: "Tail-wagging crunchy bone treat.",
  },
  {
    id: "cat_fish",
    name: "Fishy Cat Cookie",
    category: "pet",
    station: "pet",
    ingredients: { pet_mix: 1, fruit: 1 },
    steps: [
      { label: "Stir up fishy dough", durationMs: 4000 },
      { label: "Press into fish molds", durationMs: 3000 },
      { label: "Bake gently", durationMs: 3000 },
    ],
    prepMs: 10000,
    price: 5,
    unlocked: true,
    description: "Purrfectly crispy little fish.",
  },

  // ---------------- Plushies (merch, no ingredients, level 5+) ----------------
  // These are themed collectibles you grab off the shelf and wrap up.
  // Zero ingredients — you pay for them once at the supermarket by restocking
  // later — and a single short "wrap it up" step so they still flow through
  // the pastry counter prep loop like any other item.
  {
    id: "donut_bear_plush",
    name: "Donut Bear Plush",
    category: "plush",
    station: "pastry",
    ingredients: {},
    steps: [
      { label: "Pick one off the plush shelf", durationMs: 1500 },
      { label: "Tie a pink ribbon bow", durationMs: 2000 },
      { label: "Tuck into a gift box", durationMs: 2000 },
    ],
    prepMs: 5500,
    price: 18,
    unlocked: false,
    unlockLevel: 5,
    emoji: "🧸",
    description: "A teddy wearing a sprinkled donut hat — squishy and very huggable.",
    funFact: "First plushie on the merch shelf — a bakery bestseller!",
  },
  {
    id: "croissant_cat_plush",
    name: "Chocolate Croissant Cat",
    category: "plush",
    station: "pastry",
    ingredients: {},
    steps: [
      { label: "Pick one off the plush shelf", durationMs: 1500 },
      { label: "Fluff the flaky croissant tail", durationMs: 2000 },
      { label: "Wrap in crinkly paper", durationMs: 2000 },
    ],
    prepMs: 5500,
    price: 20,
    unlocked: false,
    unlockLevel: 5,
    emoji: "🐱",
    description: "Kitten curled inside a buttery croissant — too cute to resist.",
  },
  {
    id: "cupcake_bunny_plush",
    name: "Cupcake Bunny",
    category: "plush",
    station: "pastry",
    ingredients: {},
    steps: [
      { label: "Pick one off the plush shelf", durationMs: 1500 },
      { label: "Puff up the frosting ears", durationMs: 2000 },
      { label: "Pop into a sweet pastel bag", durationMs: 2000 },
    ],
    prepMs: 5500,
    price: 16,
    unlocked: false,
    unlockLevel: 5,
    emoji: "🐰",
    description: "A bunny nestled in a cupcake wrapper, with icing-swirl ears.",
  },
  {
    id: "coffee_cup_puppy_plush",
    name: "Coffee Cup Puppy",
    category: "plush",
    station: "pastry",
    ingredients: {},
    steps: [
      { label: "Lift one from the cozy shelf", durationMs: 1500 },
      { label: "Smooth out the steamy swirl", durationMs: 2000 },
      { label: "Box with a tiny tag", durationMs: 2000 },
    ],
    prepMs: 5500,
    price: 19,
    unlocked: false,
    unlockLevel: 5,
    emoji: "🐶",
    description: "A puppy peeking out of a latte cup — the cutest barista.",
  },
];

export const RECIPE_BY_ID = Object.fromEntries(
  RECIPES.map((r) => [r.id, r] as const),
) as Record<string, Recipe>;

export function recipesByCategory(category: Recipe["category"]) {
  return RECIPES.filter((r) => r.category === category);
}
